[tool.poetry]
name = "deepee"
version = "0.1.1"
description = ""
authors = ["Georgios Kaissis"]

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.8.0"
torchvision = "^0.9.0"
black = "^20.8b1"
mypy = "^0.812"
opacus = "^0.13.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
